"""Constants for the names of the known HTTP header fields."""

from enum import StrEnum


class Header(StrEnum):
    """
    The known HTTP header field names as string constants.

    The members are the field names from the `IANA HTTP field name registry
    <https://www.iana.org/assignments/http-fields/>`_ — all ``permanent``,
    ``deprecated`` and ``provisional`` registrations as of 2026-08-07
    (``obsoleted`` ones are left out) — plus a handful of widely used
    de-facto standard ``X-…`` names that were never registered.

    Being a :py:class:`enum.StrEnum`, every member *is* the header name
    string, so it can be used wherever a plain :py:class:`str` is expected:

    >>> from action0.req import Header
    >>> print(Header.CONTENT_TYPE)
    Content-Type
    >>> Header.CONTENT_TYPE == "Content-Type"
    True
    >>> Header("ETag") is Header.ETAG
    True

    ``==`` on the enum is exact, case-sensitive string equality —
    case-insensitive header handling is the job of the header mapping, not
    of these constants.
    """

    # permanent IANA registrations
    ACCEPT = "Accept"
    ACCEPT_ADDITIONS = "Accept-Additions"
    ACCEPT_CH = "Accept-CH"
    ACCEPT_DATETIME = "Accept-Datetime"
    ACCEPT_ENCODING = "Accept-Encoding"
    ACCEPT_FEATURES = "Accept-Features"
    ACCEPT_LANGUAGE = "Accept-Language"
    ACCEPT_PATCH = "Accept-Patch"
    ACCEPT_POST = "Accept-Post"
    ACCEPT_QUERY = "Accept-Query"
    ACCEPT_RANGES = "Accept-Ranges"
    ACCEPT_SIGNATURE = "Accept-Signature"
    ACCESS_CONTROL_ALLOW_CREDENTIALS = "Access-Control-Allow-Credentials"
    ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"
    ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods"
    ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin"
    ACCESS_CONTROL_EXPOSE_HEADERS = "Access-Control-Expose-Headers"
    ACCESS_CONTROL_MAX_AGE = "Access-Control-Max-Age"
    ACCESS_CONTROL_REQUEST_HEADERS = "Access-Control-Request-Headers"
    ACCESS_CONTROL_REQUEST_METHOD = "Access-Control-Request-Method"
    AGE = "Age"
    ALLOW = "Allow"
    ALPN = "ALPN"
    ALTERNATES = "Alternates"
    ALT_SVC = "Alt-Svc"
    ALT_USED = "Alt-Used"
    APPLY_TO_REDIRECT_REF = "Apply-To-Redirect-Ref"
    AUTHENTICATION_CONTROL = "Authentication-Control"
    AUTHENTICATION_INFO = "Authentication-Info"
    AUTHORIZATION = "Authorization"
    AVAILABLE_DICTIONARY = "Available-Dictionary"
    A_IM = "A-IM"
    CACHE_CONTROL = "Cache-Control"
    CACHE_GROUPS = "Cache-Groups"
    CACHE_GROUP_INVALIDATION = "Cache-Group-Invalidation"
    CACHE_STATUS = "Cache-Status"
    CALDAV_TIMEZONES = "CalDAV-Timezones"
    CAL_MANAGED_ID = "Cal-Managed-ID"
    CAPSULE_PROTOCOL = "Capsule-Protocol"
    CDN_CACHE_CONTROL = "CDN-Cache-Control"
    CDN_LOOP = "CDN-Loop"
    CERT_NOT_AFTER = "Cert-Not-After"
    CERT_NOT_BEFORE = "Cert-Not-Before"
    CLEAR_SITE_DATA = "Clear-Site-Data"
    CLIENT_CERT = "Client-Cert"
    CLIENT_CERT_CHAIN = "Client-Cert-Chain"
    CLOSE = "Close"
    CONCEALED_AUTH_EXPORT = "Concealed-Auth-Export"
    CONNECTION = "Connection"
    CONTENT_DIGEST = "Content-Digest"
    CONTENT_DISPOSITION = "Content-Disposition"
    CONTENT_ENCODING = "Content-Encoding"
    CONTENT_LANGUAGE = "Content-Language"
    CONTENT_LENGTH = "Content-Length"
    CONTENT_LOCATION = "Content-Location"
    CONTENT_RANGE = "Content-Range"
    CONTENT_SECURITY_POLICY = "Content-Security-Policy"
    CONTENT_SECURITY_POLICY_REPORT_ONLY = "Content-Security-Policy-Report-Only"
    CONTENT_TYPE = "Content-Type"
    COOKIE = "Cookie"
    CROSS_ORIGIN_EMBEDDER_POLICY = "Cross-Origin-Embedder-Policy"
    CROSS_ORIGIN_EMBEDDER_POLICY_REPORT_ONLY = "Cross-Origin-Embedder-Policy-Report-Only"
    CROSS_ORIGIN_OPENER_POLICY = "Cross-Origin-Opener-Policy"
    CROSS_ORIGIN_OPENER_POLICY_REPORT_ONLY = "Cross-Origin-Opener-Policy-Report-Only"
    CROSS_ORIGIN_RESOURCE_POLICY = "Cross-Origin-Resource-Policy"
    DASL = "DASL"
    DATE = "Date"
    DAV = "DAV"
    DELTA_BASE = "Delta-Base"
    DEPRECATION = "Deprecation"
    DEPTH = "Depth"
    DESTINATION = "Destination"
    DETACHED_JWS = "Detached-JWS"
    DICTIONARY_ID = "Dictionary-ID"
    DPOP = "DPoP"
    DPOP_NONCE = "DPoP-Nonce"
    EARLY_DATA = "Early-Data"
    ETAG = "ETag"
    EXPECT = "Expect"
    EXPIRES = "Expires"
    FORWARDED = "Forwarded"
    FROM = "From"
    HOBAREG = "Hobareg"
    HOST = "Host"
    IF = "If"
    IF_MATCH = "If-Match"
    IF_MODIFIED_SINCE = "If-Modified-Since"
    IF_NONE_MATCH = "If-None-Match"
    IF_RANGE = "If-Range"
    IF_SCHEDULE_TAG_MATCH = "If-Schedule-Tag-Match"
    IF_UNMODIFIED_SINCE = "If-Unmodified-Since"
    IM = "IM"
    INCLUDE_REFERRED_TOKEN_BINDING_ID = "Include-Referred-Token-Binding-ID"
    INCREMENTAL = "Incremental"
    KEEP_ALIVE = "Keep-Alive"
    LABEL = "Label"
    LAST_EVENT_ID = "Last-Event-ID"
    LAST_MODIFIED = "Last-Modified"
    LINK = "Link"
    LINK_TEMPLATE = "Link-Template"
    LOCATION = "Location"
    LOCK_TOKEN = "Lock-Token"
    MAX_FORWARDS = "Max-Forwards"
    MEMENTO_DATETIME = "Memento-Datetime"
    METER = "Meter"
    MIME_VERSION = "MIME-Version"
    NEGOTIATE = "Negotiate"
    NEL = "NEL"
    ODATA_ENTITYID = "OData-EntityId"
    ODATA_ISOLATION = "OData-Isolation"
    ODATA_MAXVERSION = "OData-MaxVersion"
    ODATA_VERSION = "OData-Version"
    OPTIONAL_WWW_AUTHENTICATE = "Optional-WWW-Authenticate"
    ORDERING_TYPE = "Ordering-Type"
    ORIGIN = "Origin"
    ORIGIN_AGENT_CLUSTER = "Origin-Agent-Cluster"
    OSCORE = "OSCORE"
    OSLC_CORE_VERSION = "OSLC-Core-Version"
    OVERWRITE = "Overwrite"
    PING_FROM = "Ping-From"
    PING_TO = "Ping-To"
    POSITION = "Position"
    PREFER = "Prefer"
    PREFERENCE_APPLIED = "Preference-Applied"
    PRIORITY = "Priority"
    PROXY_AUTHENTICATE = "Proxy-Authenticate"
    PROXY_AUTHENTICATION_INFO = "Proxy-Authentication-Info"
    PROXY_AUTHORIZATION = "Proxy-Authorization"
    PROXY_STATUS = "Proxy-Status"
    PUBLIC_KEY_PINS = "Public-Key-Pins"
    PUBLIC_KEY_PINS_REPORT_ONLY = "Public-Key-Pins-Report-Only"
    RANGE = "Range"
    REDIRECT_REF = "Redirect-Ref"
    REFERER = "Referer"
    REFERRER_POLICY = "Referrer-Policy"
    REFRESH = "Refresh"
    REPLAY_NONCE = "Replay-Nonce"
    REPR_DIGEST = "Repr-Digest"
    RETRY_AFTER = "Retry-After"
    SCHEDULE_REPLY = "Schedule-Reply"
    SCHEDULE_TAG = "Schedule-Tag"
    SEC_FETCH_DEST = "Sec-Fetch-Dest"
    SEC_FETCH_MODE = "Sec-Fetch-Mode"
    SEC_FETCH_SITE = "Sec-Fetch-Site"
    SEC_FETCH_USER = "Sec-Fetch-User"
    SEC_PURPOSE = "Sec-Purpose"
    SEC_TOKEN_BINDING = "Sec-Token-Binding"
    SEC_WEBSOCKET_ACCEPT = "Sec-WebSocket-Accept"
    SEC_WEBSOCKET_EXTENSIONS = "Sec-WebSocket-Extensions"
    SEC_WEBSOCKET_KEY = "Sec-WebSocket-Key"
    SEC_WEBSOCKET_PROTOCOL = "Sec-WebSocket-Protocol"
    SEC_WEBSOCKET_VERSION = "Sec-WebSocket-Version"
    SERVER = "Server"
    SERVER_TIMING = "Server-Timing"
    SET_COOKIE = "Set-Cookie"
    SET_TXN = "Set-Txn"
    SIGNATURE = "Signature"
    SIGNATURE_INPUT = "Signature-Input"
    SLUG = "SLUG"
    SOAPACTION = "SoapAction"
    STATUS_URI = "Status-URI"
    STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security"
    SUNSET = "Sunset"
    TCN = "TCN"
    TE = "TE"
    TIMEOUT = "Timeout"
    TOPIC = "Topic"
    TRACEPARENT = "Traceparent"
    TRACESTATE = "Tracestate"
    TRAILER = "Trailer"
    TRANSFER_ENCODING = "Transfer-Encoding"
    TTL = "TTL"
    UNENCODED_DIGEST = "Unencoded-Digest"
    UPGRADE = "Upgrade"
    URGENCY = "Urgency"
    USER_AGENT = "User-Agent"
    USE_AS_DICTIONARY = "Use-As-Dictionary"
    VARIANT_VARY = "Variant-Vary"
    VARY = "Vary"
    VIA = "Via"
    WANT_CONTENT_DIGEST = "Want-Content-Digest"
    WANT_REPR_DIGEST = "Want-Repr-Digest"
    WANT_UNENCODED_DIGEST = "Want-Unencoded-Digest"
    WWW_AUTHENTICATE = "WWW-Authenticate"
    X_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"
    X_FRAME_OPTIONS = "X-Frame-Options"
    __ = "*"

    # deprecated IANA registrations (still seen in the wild)
    ACCEPT_CHARSET = "Accept-Charset"
    CONTENT_ID = "Content-ID"
    C_PEP_INFO = "C-PEP-Info"
    DIFFERENTIAL_ID = "Differential-ID"
    EXPECT_CT = "Expect-CT"
    PRAGMA = "Pragma"
    PROTOCOL_INFO = "Protocol-Info"
    PROTOCOL_QUERY = "Protocol-Query"

    # provisional IANA registrations
    ACTIVATE_STORAGE_ACCESS = "Activate-Storage-Access"
    AMP_CACHE_TRANSFORM = "AMP-Cache-Transform"
    CMCD_OBJECT = "CMCD-Object"
    CMCD_REQUEST = "CMCD-Request"
    CMCD_SESSION = "CMCD-Session"
    CMCD_STATUS = "CMCD-Status"
    CMSD_DYNAMIC = "CMSD-Dynamic"
    CMSD_STATIC = "CMSD-Static"
    CONFIGURATION_CONTEXT = "Configuration-Context"
    CTA_COMMON_ACCESS_TOKEN = "CTA-Common-Access-Token"
    EDIINT_FEATURES = "EDIINT-Features"
    ISOLATION = "Isolation"
    PERMISSIONS_POLICY = "Permissions-Policy"
    REPEATABILITY_CLIENT_ID = "Repeatability-Client-ID"
    REPEATABILITY_FIRST_SENT = "Repeatability-First-Sent"
    REPEATABILITY_REQUEST_ID = "Repeatability-Request-ID"
    REPEATABILITY_RESULT = "Repeatability-Result"
    REPORTING_ENDPOINTS = "Reporting-Endpoints"
    SEC_FETCH_STORAGE_ACCESS = "Sec-Fetch-Storage-Access"
    SEC_GPC = "Sec-GPC"
    SURROGATE_CAPABILITY = "Surrogate-Capability"
    SURROGATE_CONTROL = "Surrogate-Control"
    TIMING_ALLOW_ORIGIN = "Timing-Allow-Origin"

    # unregistered de-facto standards
    X_API_KEY = "X-API-Key"
    X_CORRELATION_ID = "X-Correlation-Id"
    X_CSRF_TOKEN = "X-CSRF-Token"
    X_FORWARDED_FOR = "X-Forwarded-For"
    X_FORWARDED_HOST = "X-Forwarded-Host"
    X_FORWARDED_PROTO = "X-Forwarded-Proto"
    X_POWERED_BY = "X-Powered-By"
    X_REAL_IP = "X-Real-IP"
    X_REQUEST_ID = "X-Request-Id"
    X_ROBOTS_TAG = "X-Robots-Tag"
